server:
  port: 8083

spring:
  application:
    name: consumer

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

management:
  # 暴露监控端点web端
  endpoints:
    web:
      exposure:
        include: '*'
  # 显示服务健康具体信息
  endpoint:
    health:
      show-details: always