server:
  port: 8089
spring:
  application:
    name: sentinel
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
      eager: true
      web-context-unify: true
      datasource:
        ds1:
          file:
            file: classpath:flowrule.json
            data-type: json
            rule-type: flow

management:
  # 暴露监控端点web端
  endpoints:
    web:
      exposure:
        include: '*'
  # 显示服务健康具体信息
  endpoint:
    health:
      show-details: always